using System.Collections.Generic;
using System.IO;
using System.Linq;
using MuseXR.Worlds;
using NUnit.Framework;
using UnityEngine;
using UnityEditor;

namespace MusePico.Tests
{
    /// <summary>
    /// Pins the Small world set — Skylar's captures re-exported from Marble at 500k.
    ///
    /// Two failures these exist to catch, both of which otherwise surface only on the headset:
    ///  - an address that no converted asset answers to, which Addressables reports as a load
    ///    failure at runtime and nowhere earlier;
    ///  - a spawn drifting away from the value that 27 commits of playtesting settled on.
    /// </summary>
    public class WorldCatalogTests
    {
        /// <summary>
        /// The six that exist at both resolutions, and the values ported from the full-res
        /// entries. Written out rather than read from WorldCatalog.Skylar so that a change to
        /// EITHER list has to be made deliberately in both places.
        /// </summary>
        static readonly object[] Ported =
        {
            //          base key                                 scale  spawnX  spawnZ  groundY  yaw    far
            new object[]{"van-gogh-inspired-gallery-interior",    1.7f,  1.79f,  0.30f,  0.0f,    0f,    200f},
            new object[]{"elegant-floral-palace-interior",        1.7f,  1.16f, -2.2f,   0.2f,   25f,    200f},
            new object[]{"mexican-courtyard-bedroom-fantasy",     1.7f,  2.21f, -1.23f,  0.1f,    0f,    400f},
            new object[]{"grand-conservatory-with-lush-gardens",  1.7f, -1.6f,  -4.8f,   0.9f,    0f,    400f},
            new object[]{"enchanted-water-garden-sanctuary",      1.7f,  0.8f, -19f,     1.1f,  180f,    400f},
            new object[]{"dreamlike-coastal-villa-gardens",       1.7f, -1.6f,  -2.8f,   5.6f,    0f,    400f},
        };

        static readonly string[] Unmeasured =
        {
            "enchanted-palace-garden",
            "fantasy-realm-of-shimmering-spheres",
        };

        static WorldDefinition Find(string baseKey) =>
            WorldCatalog.Small.FirstOrDefault(w => w.key == baseKey + WorldCatalog.SmallSuffix);

        static string PathOf(string address) =>
            AssetDatabase.FindAssets("t:GaussianSplatAsset")
                .Select(AssetDatabase.GUIDToAssetPath)
                .FirstOrDefault(p => Path.GetFileNameWithoutExtension(p) == address);

        [Test]
        public void SmallSet_IsSkylarsEightPlusTheThreshold()
        {
            // Eight 500k re-exports of her captures, plus the threshold conservatory generated from
            // her hero image on 23 Sep 2026 to give stage 00 somewhere to stand. A ninth entry is
            // therefore expected. The TENTH is the same threshold capture visibility-pruned
            // (`grand-conservatory-garden-path-cut`, 25 Sep 2026, Tools/splat/prune.py). The
            // ELEVENTH is `celestial-peach-blossom-paradise` (same day), now Scene 2. The TWELFTH
            // and THIRTEENTH are Skylar's Scene 1, generated by Saul in Marble on 27 Sep 2026:
            // `imperial-courtyard-forbidden-city` (the opening stages stand there) and
            // `empty-chinese-imperial-temple-hall` (chapter 01, where the monumental Buddha
            // stands). The FOURTEENTH is the world inside Pissarro's Woman Bathing Her Feet in a
            // Brook (PaintingWorlds), made in Chisel on 1 Oct 2026. The FIFTEENTH is the Buddha Hall
            // (Chisel), where stages 05-09 happen since 1 Oct 2026 — a sixteenth means something was
            // added without a note here.
            Assert.AreEqual(15, WorldCatalog.Small.Count);

            foreach (var key in new[] { "imperial-courtyard-forbidden-city-500k", "empty-chinese-imperial-temple-hall-500k" })
            {
                var w = WorldCatalog.Small.FirstOrDefault(x => x.key == key);
                Assert.IsNotNull(w, key);
                Assert.IsTrue(w.hasMeasuredSpawn, key + ": spawn chosen by eye, not the bounds fallback");
                Assert.AreEqual(180f, w.yawDegrees, 1e-3f, key + ": faces the hall / the Buddha");
            }

            var threshold = WorldCatalog.Small
                .FirstOrDefault(w => w.key.StartsWith("grand-conservatory-garden-path"));
            Assert.IsNotNull(threshold, "the threshold world is what stage 00 stands in");
            Assert.IsTrue(threshold.hasMeasuredSpawn,
                "its bounds are 327 m of sky and terrain; the fallback would put the eye above it");
            Assert.AreEqual(180f, threshold.yawDegrees, 1e-3f,
                "yaw 0 faces the balustrade; 180 faces the glass dome, which is her composition");
        }

        [Test]
        public void EveryKey_CarriesTheSuffix_AndIsUnique()
        {
            // Six of the eight share a capture with a full-res asset, and Addressables keys off
            // the file name — without the suffix those six would collide and one would silently
            // win. This is the guard on that.
            foreach (var w in WorldCatalog.Small)
                StringAssert.EndsWith(WorldCatalog.SmallSuffix, w.key, "world " + w.displayName);

            CollectionAssert.AllItemsAreUnique(WorldCatalog.Small.Select(w => w.key).ToList());
        }

        [Test]
        public void SmallKeys_DoNotCollideWithTheFullResSet()
        {
            var full = new HashSet<string>(WorldCatalog.Skylar.Select(w => w.Address));
            foreach (var w in WorldCatalog.Small)
                Assert.IsFalse(full.Contains(w.Address),
                    "address " + w.Address + " is already taken by the full-res set");
        }

        [Test, TestCaseSource(nameof(Ported))]
        public void PortedWorlds_KeepTheirPlaytestedSpawn(
            string baseKey, float scale, float spawnX, float spawnZ,
            float groundY, float yaw, float far)
        {
            var w = Find(baseKey);
            Assert.IsNotNull(w, baseKey + " is missing from the Small set");
            Assert.IsTrue(w.hasMeasuredSpawn, baseKey + " lost its measured spawn");
            Assert.AreEqual(scale,   w.worldScale, 1e-4f, "worldScale");
            Assert.AreEqual(spawnX,  w.spawn.x,    1e-4f, "spawn.x");
            Assert.AreEqual(spawnZ,  w.spawn.y,    1e-4f, "spawn.z");
            Assert.AreEqual(groundY, w.groundY,    1e-4f, "groundY");
            Assert.AreEqual(yaw,     w.yawDegrees, 1e-4f, "yaw");
            Assert.AreEqual(far,     w.cameraFar,  1e-4f, "cameraFar");
        }

        [Test, TestCaseSource(nameof(Ported))]
        public void PortedWorlds_MatchTheFullResEntryTheyCameFrom(
            string baseKey, float scale, float spawnX, float spawnZ,
            float groundY, float yaw, float far)
        {
            // The 500k bounds sit strictly inside the full-res bounds on all six faces, which is
            // decimation rather than a change of frame — so these numbers must stay identical
            // between the two sets. If someone retunes one, this fails and forces the question.
            var full = WorldCatalog.Skylar.FirstOrDefault(x => x.key == baseKey);
            Assert.IsNotNull(full, baseKey + " is not in the full-res set");
            var small = Find(baseKey);

            Assert.AreEqual(full.worldScale, small.worldScale, 1e-4f, "worldScale");
            Assert.AreEqual(full.spawn.x,    small.spawn.x,    1e-4f, "spawn.x");
            Assert.AreEqual(full.spawn.y,    small.spawn.y,    1e-4f, "spawn.z");
            Assert.AreEqual(full.groundY,    small.groundY,    1e-4f, "groundY");
            Assert.AreEqual(full.yawDegrees, small.yawDegrees, 1e-4f, "yaw");
            Assert.AreEqual(full.cameraFar,  small.cameraFar,  1e-4f, "cameraFar");
        }

        [Test]
        public void TheTwoNewWorlds_NowCarryAMeasuredSpawn()
        {
            // Superseded 22 Sep 2026. This used to assert the opposite: that neither world could
            // claim a measured spawn, because enchanted-palace-garden is absent from worlds.js and
            // fantasy-realm's profile there is in metric space, ~11x off this .spz's extent.
            //
            // Both were then measured directly instead of ported - loaded in the Editor, camera at
            // the origin at eye height, screenshot compared at yaw 0 and 180
            // (Assets/Screenshots/probe-*.png). Both stand correctly on the floor at groundY 0,
            // which matches the six playtested worlds whose groundY runs 0.0 to 1.1, and matches
            // these being web-UI Marble exports already baked to the final world frame.
            //
            // The old fallback was the actual defect: WorldCycler.Place backs the camera off 45%
            // of the LARGER horizontal extent, which put the eye 44 m behind the palace garden and
            // just past the far z bound of the spheres - i.e. outside the capture looking in.
            foreach (var baseKey in Unmeasured)
            {
                var w = Find(baseKey);
                Assert.IsNotNull(w, baseKey + " is missing from the Small set");
                Assert.IsTrue(w.hasMeasuredSpawn,
                    baseKey + " should carry the spawn measured on 22 Sep 2026");
                Assert.AreEqual(0f, w.groundY, 1e-4f,
                    baseKey + " is a pre-baked export, so its ground sits at y=0");
                Assert.AreEqual(Vector2.zero, w.spawn,
                    baseKey + " was measured standing at the origin");
            }
        }

        [Test]
        public void EveryAddress_ResolvesToAConvertedAsset()
        {
            foreach (var w in WorldCatalog.Small)
                Assert.IsNotNull(PathOf(w.Address),
                    "no converted GaussianSplatAsset named '" + w.Address + "'. Reconvert from " +
                    "Tools/marble/smallworlds; an address with no asset fails only at runtime.");
        }

        [Test]
        public void Get_ReturnsTheRightSet()
        {
            Assert.AreSame(WorldCatalog.Small,   WorldCatalog.Get(WorldSet.Small));
            Assert.AreSame(WorldCatalog.Samples, WorldCatalog.Get(WorldSet.Samples));
            Assert.AreSame(WorldCatalog.Skylar,  WorldCatalog.Get(WorldSet.Skylar));
        }

        [Test]
        public void SpawnsSitInsideTheAssetBounds()
        {
            // A spawn outside the cloud is the "visitor starts in the sky" failure that cost
            // muse-infinity several commits. Bounds come from the asset, so this checks the
            // ported numbers against the 500k re-export rather than against the original — the
            // interiors lost 20-25% of their extent to decimation.
            foreach (var w in WorldCatalog.Small)
            {
                if (!w.hasMeasuredSpawn) continue;

                var path = PathOf(w.Address);
                Assert.IsNotNull(path, "missing asset for " + w.Address);
                var asset = AssetDatabase
                    .LoadAssetAtPath<GaussianSplatting.Runtime.GaussianSplatAsset>(path);
                Assert.IsNotNull(asset, "could not load " + path);

                Assert.IsTrue(w.spawn.x >= asset.boundsMin.x && w.spawn.x <= asset.boundsMax.x,
                    w.Address + ": spawn x " + w.spawn.x + " outside " +
                    asset.boundsMin.x + ".." + asset.boundsMax.x);
                Assert.IsTrue(w.spawn.y >= asset.boundsMin.z && w.spawn.y <= asset.boundsMax.z,
                    w.Address + ": spawn z " + w.spawn.y + " outside " +
                    asset.boundsMin.z + ".." + asset.boundsMax.z);
            }
        }

        /// <summary>
        /// The Original set is muse-infinity's worlds only, and the unmodified 500k exports only:
        /// no pruned "-cut" world, no Chisel rebuild, nothing we generated ourselves.
        /// </summary>
        [Test]
        public void OriginalIsTheSevenWebWorldsAsExported()
        {
            var original = WorldCatalog.Get(WorldSet.Original);
            Assert.AreEqual(7, original.Count, "seven of worlds.js's ten have a 500k export");

            var keys = original.Select(w => w.key).ToArray();
            CollectionAssert.AllItemsAreUnique(keys);
            foreach (var w in original)
            {
                Assert.IsTrue(WorldCatalog.Small.Contains(w), w.key + " is not the Small definition");
                StringAssert.DoesNotContain("chisel", w.key);
                StringAssert.DoesNotEndWith("-cut-500k", w.key);
            }
            CollectionAssert.DoesNotContain(keys, "enchanted-palace-garden-500k",
                "not in muse-infinity/config/worlds.js");
            CollectionAssert.AreEqual(
                WorldCatalog.OriginalKeys.Select(k => k + WorldCatalog.SmallSuffix).ToArray(), keys,
                "an OriginalKeys entry did not match any Small world");
        }
        [Test]
        public void HerWorldsFaceTheWayTheyDoInHerApp()
        {
            // Measured in her running app, 1 Oct 2026: the conservatory at yaw 0 looks toward -Z
            // (her paintings run from z -13 to -35 ahead of a spawn at z -8.16).
            var conservatory = WorldCatalog.Small.First(w => w.key == "grand-conservatory-with-lush-gardens" + WorldCatalog.SmallSuffix);
            var fwd = conservatory.SpawnRotation * Vector3.forward;
            Assert.That(fwd.z, Is.EqualTo(-1f).Within(1e-4f), "her yaw 0 is three.js -Z");
            Assert.That((conservatory.EnteredRotation * Vector3.forward).z, Is.EqualTo(1f).Within(1e-4f),
                        "door spots keep measuring from the yaw as entered");

            // The spheres' yaw was chosen here by screenshot, not copied from her.
            var spheres = WorldCatalog.Small.First(w => w.key == "fantasy-realm-of-shimmering-spheres" + WorldCatalog.SmallSuffix);
            Assert.IsFalse(spheres.yawFromWeb);
        }

        [Test]
        public void TheGalleryHangsAtHerNumbers()
        {
            // Flat ground, no walls: her first work goes on HER left (-X when facing -Z), 7 m ahead,
            // 3.2 m out, facing back to the walk line.
            var hangs = WebGalleryLayout.Place(2, new Vector3(0f, 0f, 0f), Vector3.back, null,
                                               (x, z) => 0f, (o, d, far) => null);
            Assert.That(hangs[0].centre.x, Is.EqualTo(-WebGalleryLayout.Lateral).Within(1e-3f));
            Assert.That(hangs[0].centre.z, Is.EqualTo(-7f).Within(1e-3f));
            Assert.That(hangs[1].centre.x, Is.EqualTo(WebGalleryLayout.Lateral).Within(1e-3f));
            Assert.That(hangs[1].centre.z, Is.EqualTo(-13.5f).Within(1e-3f));
        }
        [Test]
        public void ThePissarroCanBeSteppedInto()
        {
            // The painting's world must exist in the set the journey loads from, or STEP INTO THE
            // PAINTING loads nothing. Other works have no world and get no button.
            var key = PaintingWorlds.For("aic-153799");
            Assert.IsNotNull(key);
            Assert.IsTrue(WorldCatalog.Small.Any(w => w.key == key), key + " is not in WorldCatalog.Small");
            Assert.IsNull(PaintingWorlds.For("aic-81551"));
            Assert.IsNull(PaintingWorlds.For(null));
        }
    }
}
